In [1]:
import numpy as np

In [40]:
# Creamos array

a = np.random.randint(0,10, size=(10,20))
print(a)

[[2 8 1 6 3 2 6 3 5 4 5 2 4 7 7 6 9 3 6 6]
 [3 2 6 2 2 6 2 7 1 1 3 4 0 9 7 6 5 0 6 2]
 [6 8 5 9 2 8 5 1 9 2 9 4 5 1 1 5 2 0 6 9]
 [0 7 6 8 5 8 9 0 4 3 2 4 0 6 7 3 7 5 5 6]
 [2 7 0 7 2 0 5 4 1 6 3 6 1 9 9 0 0 3 2 5]
 [1 7 8 9 3 2 1 3 9 5 2 6 0 0 2 0 9 5 8 9]
 [9 4 2 3 5 6 5 8 3 7 5 4 2 6 6 9 9 5 0 1]
 [0 5 4 3 7 6 0 3 6 9 4 7 7 8 1 4 9 0 6 6]
 [2 0 5 9 3 7 1 8 0 3 8 0 3 5 8 9 8 9 3 6]
 [4 8 4 0 5 2 2 2 8 8 6 5 6 0 2 4 0 8 9 0]]


In [41]:
b = np.arange(19,-1,-1)

In [42]:
c = a.copy()
for i in range(0,20):
    c[:,i] = a[:,b[i]]

In [44]:
d = a[:,b]

In [45]:
print(c)

[[6 6 3 9 6 7 7 4 2 5 4 5 3 6 2 3 6 1 8 2]
 [2 6 0 5 6 7 9 0 4 3 1 1 7 2 6 2 2 6 2 3]
 [9 6 0 2 5 1 1 5 4 9 2 9 1 5 8 2 9 5 8 6]
 [6 5 5 7 3 7 6 0 4 2 3 4 0 9 8 5 8 6 7 0]
 [5 2 3 0 0 9 9 1 6 3 6 1 4 5 0 2 7 0 7 2]
 [9 8 5 9 0 2 0 0 6 2 5 9 3 1 2 3 9 8 7 1]
 [1 0 5 9 9 6 6 2 4 5 7 3 8 5 6 5 3 2 4 9]
 [6 6 0 9 4 1 8 7 7 4 9 6 3 0 6 7 3 4 5 0]
 [6 3 9 8 9 8 5 3 0 8 3 0 8 1 7 3 9 5 0 2]
 [0 9 8 0 4 2 0 6 5 6 8 8 2 2 2 5 0 4 8 4]]


In [46]:
print(d)

[[6 6 3 9 6 7 7 4 2 5 4 5 3 6 2 3 6 1 8 2]
 [2 6 0 5 6 7 9 0 4 3 1 1 7 2 6 2 2 6 2 3]
 [9 6 0 2 5 1 1 5 4 9 2 9 1 5 8 2 9 5 8 6]
 [6 5 5 7 3 7 6 0 4 2 3 4 0 9 8 5 8 6 7 0]
 [5 2 3 0 0 9 9 1 6 3 6 1 4 5 0 2 7 0 7 2]
 [9 8 5 9 0 2 0 0 6 2 5 9 3 1 2 3 9 8 7 1]
 [1 0 5 9 9 6 6 2 4 5 7 3 8 5 6 5 3 2 4 9]
 [6 6 0 9 4 1 8 7 7 4 9 6 3 0 6 7 3 4 5 0]
 [6 3 9 8 9 8 5 3 0 8 3 0 8 1 7 3 9 5 0 2]
 [0 9 8 0 4 2 0 6 5 6 8 8 2 2 2 5 0 4 8 4]]
